channels:
  - conda-forge
  - bioconda
  - nvidia
  - pytorch
dependencies:
  - pip:
      - biopython==1.79
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - typing-extensions==4.3.0
      - einops
      - pyarrow
      - pandas
      - colossalai
      - absl-py==1.0.0
      - chex==0.0.7
      - contextlib2==21.6.0
      - dm-haiku==0.0.9
      - dm-tree==0.1.6
      - immutabledict==2.0.0
      - jax==0.3.25
      - jinja2==3.0.3
      - ml-collections==0.1.0
      - numpy==1.21.6
      - nvidia-ml-py3==7.352.0
      - pandas==1.3.4
      - sqlalchemy==1.3.19
      - tensorflow-cpu==2.9.0
      - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - jaxlib==0.3.25+cuda11.cudnn805
      - --pre triton
  - pytorch::pytorch=1.12
  - pytorch::torchvision
  - pytorch::torchaudio
  - conda-forge::cudatoolkit=11.3
  - conda-forge::python=3.8
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm=7.5.1
  - conda-forge::pdbfixer
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - matplotlib=3.5.1
  - pyqt=5.9.2
  - pymol-open-source
  - libxscrnsaver-cos6-x86_64=1.2.2
  - sip=4.19.13