channels:
  - anaconda
  - bioconda
  - nvidia
  - conda-forge
  - r
  - defaults
dependencies:
  - cudatoolkit=11.1.74
  - cudnn=8.0.4
  - hhsuite=3.3.0
  - hmmer=3.3.2
  - kalign3=3.2.2
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - openmm=7.5.1
  - pdbfixer=1.7
  - pyqt=5.9.2
  - pymol-open-source
  - python=3.8.12
  - qt=5.9.7
  - libxscrnsaver-cos6-x86_64=1.2.2
  - sip=4.19.13
  - pip=21.3.1
  - pip:
    - absl-py==0.13.0
    - biopython==1.79
    - chex==0.0.7
    - contextlib2==21.6.0
    - dm-haiku==0.0.4
    - dm-tree==0.1.6
    - immutabledict==2.0.0
    - jax==0.2.14
    - jinja2==3.0.3
    - ml-collections==0.1.0
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - pandas==1.3.4
    - scipy==1.7.0
    - sqlalchemy==1.3.19
    - tensorflow-cpu==2.5.0
